#!/bin/bash

[[ -z $(which java) ]] && echo "Error: Java is not installed." >&2 && exit 1

JAR=$(dirname $0)/a4download.jar

[[ ! -f ${JAR} ]] && echo "Error: ${JAR} is not found." >&2 && exit 2

java -jar ${JAR} "$@"